### ISSUE TITLE
RandomMandala not usable in Kaggle (Conda) environment | FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.10/site-packages/numpy-1.24.3.dist-info/METADATA'

### ISSUE THREAD

**Issue by maifeeulasad** [antononcube/Python-packages#1]
I'm trying to install `RandomMandala` using:
```
# !python3 -m pip install RandomMandala
!pip install RandomMandala
```

But, I'm getting this error:
```
Collecting RandomMandala
  Using cached RandomMandala-0.6.0-py3-none-any.whl (14 kB)
Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from RandomMandala) (1.23.5)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.10/site-packages (from RandomMandala) (3.6.3)
Collecting bezier (from RandomMandala)
  Using cached bezier-2021.2.12.tar.gz (313 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3031, in _dep_map
          return self.__dep_map
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2828, in __getattr__
          raise AttributeError(attr)
      AttributeError: _DistInfoDistribution__dep_map
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3022, in _parsed_pkg_info
          return self._pkg_info
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2828, in __getattr__
          raise AttributeError(attr)
      AttributeError: _pkg_info. Did you mean: 'egg_info'?
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-og5sze4x/bezier_c96cd641c45245f4a824bda802205273/setup.py", line 278, in <module>
          main()
        File "/tmp/pip-install-og5sze4x/bezier_c96cd641c45245f4a824bda802205273/setup.py", line 274, in main
          setup()
        File "/tmp/pip-install-og5sze4x/bezier_c96cd641c45245f4a824bda802205273/setup.py", line 254, in setup
          ext_modules=extension_modules(),
        File "/tmp/pip-install-og5sze4x/bezier_c96cd641c45245f4a824bda802205273/setup.py", line 144, in extension_modules
          numpy_include_dir(),
        File "/tmp/pip-install-og5sze4x/bezier_c96cd641c45245f4a824bda802205273/setup.py", line 92, in numpy_include_dir
          if not is_installed("numpy >= 1.9.0"):
        File "/tmp/pip-install-og5sze4x/bezier_c96cd641c45245f4a824bda802205273/setup.py", line 83, in is_installed
          pkg_resources.require(requirement)
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 891, in require
          needed = self.resolve(parse_requirements(requirements))
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 785, in resolve
          new_requirements = dist.requires(req.extras)[::-1]
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2749, in requires
          dm = self._dep_map
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3033, in _dep_map
          self.__dep_map = self._compute_dependencies()
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3042, in _compute_dependencies
          for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3024, in _parsed_pkg_info
          metadata = self.get_metadata(self.PKG_INFO)
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1412, in get_metadata
          value = self._get(path)
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1616, in _get
          with open(path, 'rb') as stream:
      FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.10/site-packages/numpy-1.24.3.dist-info/METADATA'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

NB, I have done other tasks such as setting the environment variable as per bezier librarie's need:
```
!mkdir tem
import os
os.environ["BEZIER_INSTALL_PREFIX"] = "/tem"
```

Can anyone help me fix it?

**Comment by antononcube** [comment]
Thanks for using this package! 

If I understand the log correctly the "numpy" library installed in your environment is behind the required by the "bezier" library.

Compare the lines:

> Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from RandomMandala) (1.23.5)

vs 

>   FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.10/site-packages/numpy-1.24.3.dist-info/METADATA'

**Comment by maifeeulasad** [comment]
I tried with this also:
```
!pip install numpy==1.24.3
```
Then I faced this issue:
```
Collecting numpy==1.24.3
  Downloading numpy-1.24.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 48.9 MB/s eta 0:00:0000:0100:01
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
apache-beam 2.46.0 requires dill<0.3.2,>=0.3.1.1, but you have dill 0.3.6 which is incompatible.
momepy 0.6.0 requires shapely>=2, but you have shapely 1.8.5.post1 which is incompatible.
pymc3 3.11.5 requires numpy<1.22.2,>=1.15.0, but you have numpy 1.24.3 which is incompatible.
pymc3 3.11.5 requires scipy<1.8.0,>=1.7.3, but you have scipy 1.10.1 which is incompatible.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.3 which is incompatible.
ydata-profiling 4.1.2 requires numpy<1.24,>=1.16.0, but you have numpy 1.24.3 which is incompatible.
ydata-profiling 4.1.2 requires scipy<1.10,>=1.4.1, but you have scipy 1.10.1 which is incompatible.
Successfully installed numpy-1.24.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: [https://pip.pypa.io/warnings/venv](https://pip.pypa.io/warnings/venv%3C/span%3E%3Cspan) class="ansi-yellow-fg">
Collecting RandomMandala
  Downloading RandomMandala-0.6.0-py3-none-any.whl (14 kB)
Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from RandomMandala) (1.24.3)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.10/site-packages (from RandomMandala) (3.6.3)
Collecting bezier (from RandomMandala)
  Downloading bezier-2021.2.12.tar.gz (313 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 313.9/313.9 kB 6.3 MB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pillow in /opt/conda/lib/python3.10/site-packages (from RandomMandala) (9.5.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib->RandomMandala) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.10/site-packages (from matplotlib->RandomMandala) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib->RandomMandala) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib->RandomMandala) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib->RandomMandala) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib->RandomMandala) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.10/site-packages (from matplotlib->RandomMandala) (2.8.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->RandomMandala) (1.16.0)
Building wheels for collected packages: bezier
  Building wheel for bezier (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/_triangle_helpers.py -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/_geometric_intersection.py -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/__init__.py -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/_intersection_helpers.py -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/_legacy.py -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/_base.py -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/_helpers.py -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/triangle.py -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/_symbolic.py -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/_curve_helpers.py -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/_triangle_intersection.py -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/_plot_helpers.py -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/curve.py -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/curved_polygon.py -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/__config__.py -> build/lib.linux-x86_64-3.10/bezier
      creating build/lib.linux-x86_64-3.10/bezier/hazmat
      copying src/python/bezier/hazmat/geometric_intersection.py -> build/lib.linux-x86_64-3.10/bezier/hazmat
      copying src/python/bezier/hazmat/__init__.py -> build/lib.linux-x86_64-3.10/bezier/hazmat
      copying src/python/bezier/hazmat/algebraic_intersection.py -> build/lib.linux-x86_64-3.10/bezier/hazmat
      copying src/python/bezier/hazmat/triangle_helpers.py -> build/lib.linux-x86_64-3.10/bezier/hazmat
      copying src/python/bezier/hazmat/helpers.py -> build/lib.linux-x86_64-3.10/bezier/hazmat
      copying src/python/bezier/hazmat/curve_helpers.py -> build/lib.linux-x86_64-3.10/bezier/hazmat
      copying src/python/bezier/hazmat/intersection_helpers.py -> build/lib.linux-x86_64-3.10/bezier/hazmat
      copying src/python/bezier/hazmat/clipping.py -> build/lib.linux-x86_64-3.10/bezier/hazmat
      copying src/python/bezier/hazmat/triangle_intersection.py -> build/lib.linux-x86_64-3.10/bezier/hazmat
      copying src/python/bezier/_curve.pxd -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/_helpers.pxd -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/_triangle.pxd -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/_curve_intersection.pxd -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/_triangle_intersection.pxd -> build/lib.linux-x86_64-3.10/bezier
      copying src/python/bezier/_status.pxd -> build/lib.linux-x86_64-3.10/bezier
      running build_ext
      building 'bezier._speedup' extension
      creating build/temp.linux-x86_64-3.10
      creating build/temp.linux-x86_64-3.10/src
      creating build/temp.linux-x86_64-3.10/src/python
      creating build/temp.linux-x86_64-3.10/src/python/bezier
      gcc -pthread -B /opt/conda/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/include -fPIC -O2 -isystem /opt/conda/include -fPIC -I/opt/conda/lib/python3.10/site-packages/numpy/core/include -I/tem/include -I/opt/conda/include/python3.10 -c src/python/bezier/_speedup.c -o build/temp.linux-x86_64-3.10/src/python/bezier/_speedup.o
      In file included from /opt/conda/lib/python3.10/site-packages/numpy/core/include/numpy/ndarraytypes.h:1940,
                       from /opt/conda/lib/python3.10/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                       from /opt/conda/lib/python3.10/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                       from src/python/bezier/_speedup.c:611:
      /opt/conda/lib/python3.10/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
         17 | #warning "Using deprecated NumPy API, disable it with " \
            |  ^~~~~~~
      src/python/bezier/_speedup.c:613:10: fatal error: bezier/curve.h: No such file or directory
        613 | #include "bezier/curve.h"
            |          ^~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bezier
  Running setup.py clean for bezier
Failed to build bezier
ERROR: Could not build wheels for bezier, which is required to install pyproject.toml-based projects
```

*I simply didn't want to install specific version of numpy as it may break my environment, which is already working.*

**Comment by antononcube** [comment]
> I simply didn't want to install specific version of numpy as it may break my environment, which is already working.

That is understandable.

Try to install "bezier" without the native libraries. See [here](https://github.com/dhermes/bezier#installing):


```
$ BEZIER_NO_EXTENSION=true \
>   python   -m pip install --upgrade bezier --no-binary=bezier
```

**Comment by maifeeulasad** [comment]
Thanks, it actually worked. I was able to set it up in all environments.

If I get some time, I'll surely post all the issues I faced.

Thanks a lot.
